endpoint:
  port: 80
  type: http

register: true
registry:
  url:   http://iw-a8registry-dev.mybluemix.net
  poll:  5s

proxy: false
proxy_adapter: envoy
proxy_config:
  working_dir: etc/envoy
  logging_dir: var/log

controller:
  url:   http://iw-a8controller-dev.mybluemix.net
  poll:  5s

log_level: debug

commands:
  - cmd: [ "python", "-u", "app.py" ]
    on_exit: terminate
