endpoint:
  port: 80
  type: http

register: true
registry:
  url:   http://iw-a8registry-dev.mybluemix.net
  poll:  5s

#proxy: true
controller:
  url:   http://iw-a8controller-dev.mybluemix.net
  poll:  5s

commands:
  - cmd: [ "python", "-u", "app.py" ]
    on_exit: terminate

log_level: debug
